prometheus:
  serviceAccount:
    create: true
    name: ${amp_sa}
    annotations:
      eks.amazonaws.com/role-arn: ${amp_irsa}
  prometheusSpec:
    remoteWrite:
      - url: ${amp_remotewrite_url}
        sigv4:
          region: ${region}
        queueConfig:
          maxSamplesPerSend: 1000
          maxShards: 200
          capacity: 2500
    retention: 5h
    scrapeInterval: 30s
    evaluationInterval: 30s
    scrapeTimeout: 10s
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
alertmanager:
  enabled: false

grafana:
  additionalDataSources:
    - name: amazon-managed-prometheus
      type: prometheus
      isDefault: true
      url: ${amp_url}
      editable: true
      jsonData:
        sigV4Auth: true
        sigV4Region: ${region}
  enabled: true
  defaultDashboardsEnabled: true
  # Adding Amazon Managed Prometheus datasource to Grafana config
  serviceAccount:
    create: false
    name: ${amp_sa}
  grafana.ini:
    auth:
      sigv4_auth_enabled: true